version: '3.8'
name: go-web
services:
  mysql:
    image: mysql:8.0.35
    container_name: go-web-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: redis:7
    container_name: redis7
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    ports:
      - "6379:6379"
    restart: always
